### PR TITLE
Pointing to CDLR archive on GitHub

### PR DESCRIPTION
**Pull request by mcallisto**

### CODE REVIEW

**Comment by cquiroz** [comment]
Thanks, it seems a test is failing, maybe the cldr version has be changed on the test?

**Comment by mcallisto** [comment]
File now downloaded, but still failing... Not sure why.

**Comment by cquiroz** [comment]
Darn, it seems they change the structure of the files too. It will require more work

**Comment by mcallisto** [comment]
Gave it a fair amount of tries but no success...

**Comment by cquiroz** [comment]
Looking at the error it seems the structure of the zip file changed and that will require extra work on the code.
I'll try to take a look ASAP

**Comment by cquiroz** [comment]
Thanks for the PR. I think it should be fixed by #80

**Pull request closed without merging**
